package com.resumeforge.analysis.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class AIResumeGenerationResponseDto {

    /**
     * Complete ATS-optimized resume generated by AI.
     */
    private String generatedResume;
}